### ISSUE TITLE
TempBans / Other Commands

### ISSUE THREAD

**Issue by TeeKay1** [yPedx/SuchBans#15] opened 2017-05-04 09:48 UTC
So i am trying to do tempbans and its giving me an error in-game where i need to add <playername> <datediff> <reason>. I cant figure out why its not working. Also I'm trying to add 2 commands to 1 ban (demote and tempban) and same issue as just the tempban...keeps giving me the same error.

**Comment by yPedx** [comment] 2017-05-04 10:45
1. You cannot add more commands, this will hopefully be added in the future.

2. Could you show me your config?
3. Could you show me the error(s)?

**Comment by TeeKay1** [comment] 2017-05-04 10:47
the error is in game, but heres config pastebin: https://pastebin.com/peHiabQy

**Comment by yPedx** [comment] 2017-05-04 11:05
If it is an internal error, it's in the console. If so, post the error from the console.

1. You never used #target (the target you are punishing, anyway, this is not the cause of the error).

2. Is ELYTRA a valid item? Haven't tested myself.

**Comment by TeeKay1** [comment] 2017-05-04 11:14
if i use the #target it turns greys and erases itself. and its not an internal error. Yes the elytra is a valid item. Im not sure the full command to tempban the target for a certain time. Basically the error states /tempban<player> <datediff> <reason>. So its not actually giving the tempban because its not recognizing that the person im targeting is the person i want to tempban, so it wants me to type the persons name everytime i want to tempban.

**Comment by yPedx** [comment] 2017-05-04 11:27
If the message/error says it's the wrong format/usage, it is not a medsage from SuchBansGUI. You'll have to look up whatever plugin you are using for that command for the correct format.

**Comment by TeeKay1** [comment] 2017-05-06 04:39
ok so i use essentialsX for the tempban and i cant find the right "player" alias to use. Nothing is working.

**Comment by yPedx** [comment] 2017-05-06 09:54
There is no player alias. Hwta I mean is;

Example tempban command to put in the GUI config;
tempban #target 5m some random reason

This will ban the targetted player for 5 minutes.
Please post your config for SuchBansGUI.

**Comment by TeeKay1** [comment] 2017-05-06 10:00
https://pastebin.com/FU73FKi5

**Comment by TeeKay1** [comment] 2017-05-06 10:01
and i tried the #target and it greys out the rest after the #

**Comment by TeeKay1** [comment] 2017-05-06 10:02
and then it erases it

**Comment by yPedx** [comment] 2017-05-06 10:26
Are you adding the item with in-game commands? Do not reload the plugin or server.

**Comment by TeeKay1** [comment] 2017-05-06 10:27
no it works adding the item in the config. I can try adding it via in-game commands though. Will that help?

**Comment by yPedx** [comment] 2017-05-06 10:28
It's much easier with the commands. However you have everything right, you just never specified the target.

**Comment by TeeKay1** [comment] 2017-05-06 10:57
i put #target and when i tried it it erased it from the config

**Comment by yPedx** [comment] 2017-05-06 11:02
Could you tell me what exactly you are doing? This should not happen by default.

**Comment by TeeKay1** [comment] 2017-05-06 11:04
Slot12:
    Name: Xray/Hacking
    Command: tempban #target 1d Xray/Hacking
    Item: DIAMOND_ORE
    Permission: sb.punish

That is exactly what i wrote. but when i run the command it erases "#target 1d Xray/Hacking"

**Comment by TeeKay1** [comment] 2017-05-06 11:05
could it be the editing program im using? I use brackets.

**Comment by yPedx** [comment] 2017-05-06 11:07
What server type are you running?

**Comment by TeeKay1** [comment] 2017-05-06 11:13
spigot 1.11.2

**Comment by yPedx** [comment] 2017-05-06 11:14
Here's an example of an item in the GUI;
```
Page1:
  Slot10:
    Name: '&eConfigure me!'
    Command: 'kick #target '
    Item: DIAMOND_SWORD
    Permission: custom.hi`
```

**Comment by TeeKay1** [comment] 2017-05-06 11:20
so a kick is basically a temp ban?

**Comment by yPedx** [comment] 2017-05-06 11:21
No xD A kick just kicks the player off the server, and he may rejoin. A tempban bans the player for a certain time you have set.

**Comment by TeeKay1** [comment] 2017-05-06 11:22
thats what i thought. that example confused me

**Comment by yPedx** [comment] 2017-05-06 11:22
It was an example usage of how to make an item. Basically showing the ' and ' on the command and name.

**Comment by TeeKay1** [comment] 2017-05-06 11:22
OHHHHH ok

**Comment by TeeKay1** [comment] 2017-05-06 11:24
IT'S ALIVE. Thanks man...big help

**Comment by yPedx** [comment] 2017-05-06 11:25
No problem. :) Closing issue.

**Closed by yPedx** 2017-05-06 11:25 UTC
